### ISSUE TITLE
Would `stdpath("state")` be a better fit for `db_root`?

### ISSUE THREAD

**Issue by adrian5** [nvim-telescope/telescope-frecency.nvim#200]
I wonder if that would be a better default for transient data of this nature (similar to shada). What do you think?

**Comment by delphinus** [comment]
I see. This plugin was born in 2021-01-14 according to commit logs. In those days, XDG_STATE_HOME did not exist because the first spec for XDG Base Directory is version 0.8 which is published in May 2021 (mentioned [here](https://unix.stackexchange.com/a/699335)).

XDG_DATA_HOME should store persistent data for applications, so frecency DB should be stored in XDG_STATE_HOME.

I will update the default place to XDG_STATE_HOME, but also add a fallback logic to search XDG_DATA_HOME.
