### ISSUE TITLE
Using `:CWD:` as workspace is very slow

### ISSUE THREAD

**Issue by HoldenLucas** [nvim-telescope/telescope-frecency.nvim#52]
Following the suggestion in the [configuration section of the readme](https://github.com/nvim-telescope/telescope-frecency.nvim/tree/979a6f3d882b7b5352cc6a751faa9c9427d40e74#configuration) to set `default_workspace` to `:CWD:` introduces ~2 seconds of loading before the results are shown. The same behavior can be observed when using the default configuration and typing `:CWD:` in the frecency prompt.

**Comment by technicalpickles** [comment]
Do you see the same thing with setting it to juts `CWD`? That is what the README currently says, and I'm not seeing a delay when using it.

**Comment by lucc** [comment]
How do you set `default_workspace` exactly?  In #55 it seems not to  work no matter what I try.

**Comment by technicalpickles** [comment]
This is what I have:

```
require("telescope").setup({
    extensions = {
        frecency = {
            default_workspace = "CWD",
            show_filter_column = false,
        },
    },
})
```

**Comment by kamalarieff** [comment]
I'm also having this issue. I've tried calling `:Telescope frecency workspace=CWD` and setting the `default_workspace = "CWD"`. Both are slow.

**Comment by delphinus** [comment]
This problem is because `show_unindexed` is `true` in default. When it is `true`, it adds all files found in the workspace.

https://github.com/nvim-telescope/telescope-frecency.nvim/blob/65a7d89eb8ee1a8ac9e88f0eb6d30fa766d21269/lua/telescope/_extensions/frecency/db_client.lua#L164-L176

When you launch Neovim in your home directory, it scans huge amount of files and takes long time. I think you should set `show_unindexed = false` if you use `default_workspace = 'CWD'`.

**Comment by delphinus** [comment]
And you may have interests to move cwd automatically when editing files, such as using [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim).

**Comment by HoldenLucas** [comment]
https://github.com/nvim-telescope/telescope-frecency.nvim/issues/52#issuecomment-1256902653 thanks @delphinus, closing
